all:
	mkdir -p OUT/
	em++ main.cpp -o OUT/main.html -g -std=c++20 -pthread -sPTHREAD_POOL_SIZE=2 -sALLOW_MEMORY_GROWTH -s EXIT_RUNTIME=0

#    Extra debug options
# 	-sSAFE_HEAP  -sASSERTIONS=2
# 	-fsanitize=address -fsanitize=undefined
